"""
data files written next to the html:

    site/js/search-index.js   the search index, as a plain script so it also
                              works when the site is opened straight from disk
    site/data/history.json    everything, for anyone who wants the raw data
    site/data/events.tsv      the timeline as tab separated text, read by the
                              c, c++ and awk tools in tools/
"""

import json
import os
import re

from .database import life_known
from .util import strip_tags, write


def _sections(page):
    """split a part's or topic's html into (id, heading, plain text) chunks at each heading."""
    parts = re.split(r'<h[23] id="([^"]+)">(.*?)</h[23]>', page.doc.html)
    out = []
    for hid, head, body in zip(parts[1::3], parts[2::3], parts[3::3]):
        out.append((hid, strip_tags(head), strip_tags(body)))
    return out


def search_index(s):
    items = []
    for e in s.eras:
        items.append(dict(k="part", t=f"part {e.number}: {e.title}", d=f"{e.start_date} – {e.end_date}",
                          x=e.summary, u=f"{e.slug}.html"))
        for hid, head, text in _sections(e):
            items.append(dict(k="section", t=head, d=f"part {e.number}", x=text[:600],
                              u=f"{e.slug}.html#{hid}"))
    for t in s.topics:
        items.append(dict(k="topic", t=t.title, d="topic", x=t.summary, u=f"{t.slug}.html"))
        for hid, head, text in _sections(t):
            items.append(dict(k="section", t=head, d=t.title, x=text[:600], u=f"{t.slug}.html#{hid}"))
    for r in s.religions:
        items.append(dict(k="religion", t=r.name, d="religion", x=r.summary, u=f"{r.slug}/index.html"))
        for hid, head, text in _sections(r):
            items.append(dict(k="religion", t=head, d=r.name, x=text[:600], u=f"{r.slug}/index.html#{hid}"))
        for ev in r.events:
            items.append(dict(k="religion", t=ev.text, d=f"{r.name}, {ev.kind}: {ev.shown}", x="",
                              u=f"{r.slug}/timeline.html#event-{ev.id}"))
        for p in r.people:
            items.append(dict(k="religion", t=p.name, d=f"{r.name}: {p.dates}", x=f"{p.role}. {p.about}",
                              u=f"{r.slug}/people.html#{p.slug}"))
        for t in r.terms:
            items.append(dict(k="religion", t=t.term, d=r.name, x=t.definition,
                              u=f"{r.slug}/glossary.html#{t.slug}"))
    for ev in s.events:
        items.append(dict(k="event", t=ev.text, d=str(ev.when), x=" ".join(ev.tags),
                          u=f"timeline.html#event-{ev.id}", y=ev.when.start))
    for p in s.people:
        items.append(dict(k="person", t=p.name, d=str(p.life), x=f"{p.role}. {p.about}",
                          u=f"people.html#{p.slug}"))
    for t in s.terms:
        items.append(dict(k="term", t=t.term, d="", x=t.definition, u=f"glossary.html#{t.slug}"))
    return items


def write_all(s, out):
    index = search_index(s)
    js = (
        "/* generated by the builder. do not edit by hand. */\n"
        "var search_index = " + json.dumps(index, ensure_ascii=False, separators=(",", ":")) + ";\n"
    )
    write(os.path.join(out, "js", "search-index.js"), js)

    everything = dict(
        eras=[dict(slug=e.slug, number=e.number, title=e.title, starts=str(e.start_date),
                   ends=str(e.end_date), summary=e.summary) for e in s.eras],
        events=[dict(id=ev.id, date=str(ev.when), start=ev.when.start, end=ev.when.end,
                     text=ev.text, era=ev.era, region=ev.region_rec.slug, tags=ev.tags)
                for ev in s.events],
        people=[dict(slug=p.slug, name=p.name, dates=str(p.life), born=p.life.start, died=p.life.end,
                     known=life_known(p), role=p.role, about=p.about, era=p.era,
                     region=p.region_rec.slug) for p in s.people],
        glossary=[dict(term=t.term, definition=t.definition) for t in s.terms],
        topics=[dict(slug=t.slug, title=t.title, summary=t.summary) for t in s.topics],
        religions=[dict(slug=r.slug, name=r.name, began=r.began, followers=r.followers,
                        creation=r.creation, age=r.age,
                        events=[dict(kind=ev.kind, when=ev.shown, text=ev.text) for ev in r.events],
                        people=[dict(name=p.name, dates=p.dates, kind=p.kind, role=p.role) for p in r.people],
                        glossary=[dict(term=t.term, definition=t.definition) for t in r.terms])
                   for r in s.religions],
    )
    write(os.path.join(out, "data", "history.json"),
          json.dumps(everything, ensure_ascii=False, indent=1) + "\n")

    # tsv columns: start year, end year, date text, part number, region, event text
    rows = ["# start\tend\tdate\tpart\tregion\ttext"]
    for ev in s.events:
        clean = lambda v: str(v).replace("\t", " ").replace("\n", " ")
        rows.append("\t".join(clean(v) for v in (
            f"{ev.when.start:.0f}", f"{ev.when.end:.0f}", ev.when, ev.era_rec.number,
            ev.region_rec.name, ev.text)))
    write(os.path.join(out, "data", "events.tsv"), "\n".join(rows) + "\n")
    return len(index)
